blank_issues_enabled: false
contact_links:
  - name: lentod Discussions
    url: https://github.com/lentod/hugo-lentod/discussions
    about: Please ask and answer questions/doubts here, DO NOT open an issue for questions.
